name: Metrics
on:
  # Schedule updates (every hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: manojbhargavan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata # Set your timezone

          # --- Plugins ---
          
          # Isometric Calendar (The 3D block contribution view)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Languages (The bar chart of languages you use)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage

          # Lines of code changed
          plugin_lines: yes

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_leetcode: yes
          plugin_leetcode_user: manojbhargavan
